# Generated by Django 3.2.7 on 2021-10-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='processing_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
