# Generated by Django 3.2.7 on 2021-09-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
