# Generated by Django 3.2.7 on 2021-10-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cart_processing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='processing_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
