# Generated by Django 3.2.7 on 2021-09-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Discount, in %'),
        ),
    ]
